export const DELETE_TODO = 'DELETE_TODO';

export const GET_POST_DATA = 'GET_POST_DATA';
export const GET_POST_SUCCEEDED = 'GET_POST_SUCCEEDED';
export const GET_POST_FAILED = 'GET_POST_FAILED';


export const DELETE_POST = 'DELETE_POST';

export const GET_BASKETBALL_TEAMS = 'GET_BASKETBALL_TEAMS';
export const GET_BASKETBALL_TEAMS_SUCCEEDED = 'GET_BASKETBALL_TEAMS_SUCCEEDED';
export const GET_BASKETBALL_TEAMS_FAILED = 'GET_BASKETBALL_TEAMS_FAIED';

export const GET_BASKETBALL_SCORES = 'GET_BASKETBALL_SCORES';
export const GET_BASKETBALL_SCORES_SUCCEEDED = 'GET_BASKETBALL_SCORES_SUCCEEDED';
export const GET_BASKETBALL_SCORES_FAILED = 'GET_BASKETBALL_SCORES_FAIED';